SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count
FROM RETAIL_DB.RAW.CUSTOMERS

UNION ALL

SELECT 'PRODUCTS', COUNT(*)
FROM RETAIL_DB.RAW.PRODUCTS

UNION ALL

SELECT 'STORES', COUNT(*)
FROM RETAIL_DB.RAW.STORES

UNION ALL

SELECT 'ORDERS', COUNT(*)
FROM RETAIL_DB.RAW.ORDERS

UNION ALL

SELECT 'PAYMENTS', COUNT(*)
FROM RETAIL_DB.RAW.PAYMENTS

UNION ALL

SELECT 'RETURNS', COUNT(*)
FROM RETAIL_DB.RAW.RETURNS;